### ISSUE TITLE
Add Samsung Internet logo image?

### ISSUE THREAD

**Issue by cvrebert** [whatwg/resources.whatwg.org#18]
It's the only browser in the HTML spec's CanIUse boxes which doesn't currently show a logo.
X-Ref: https://github.com/alrra/browser-logos/tree/master/samsung-internet

**Comment by zcorpan** [comment]
Thanks!

**Comment by jungkees** [comment]
@cvrebert, thanks a lot for having brought this!

/cc @torgo
