### ISSUE TITLE
dfn.js doesn't work with Bikeshed dfn headings

### ISSUE THREAD

**Issue by annevk** [whatwg/resources.whatwg.org#26]
I noticed this just after I landed https://github.com/whatwg/encoding/pull/79.

I believe Bikeshed also includes this functionality now, but @domenic had some concerns, right?

**Comment by domenic** [comment]
Basically Bikeshed's doesn't work on mobile as well as dfn.js does; see https://github.com/tabatkins/bikeshed/issues/469#issuecomment-187795863
