### ISSUE TITLE
Make dfn.js work for multipage HTML

### ISSUE THREAD

**Issue by zcorpan** [whatwg/resources.whatwg.org#36]
Maybe it can use multipage/fragment-links.json somehow? It's already XHR'ed (sometimes) to do redirects.

cc @nox

**Comment by zcorpan** [comment]
Hmm no fragment-links.json doesn't have data about instances...

**Comment by zcorpan** [comment]
I think we'd need a Web service to do this. And that could also support multiple specs, which would be pretty awesome.

**Comment by domenic** [comment]
The current plan was to bake the functionality into Wattsi instead of generating it at runtime.

**Comment by nox** [comment]
Any progress on this?

**Comment by foolip** [comment]
Moved this to https://github.com/whatwg/whatwg.org/issues/63 so it's not forgotten.
