### ISSUE TITLE
Use Travis to deploy resources.whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/resources.whatwg.org#42]
I think ideally we use the same tactic as we do for whatwg.org.

Things we could do with Travis:

* Check the SVG (both parsing and conformance)
* Check the JSON (parsing)

We could even start linting our JavaScript and checking our CSS and such. And making sure PNGs are optimized and whatnot.

**Comment by foolip** [comment]
How does this currently work, is it manual? Folding this repo into the whatwg.org repo would make this quite simple, any objections to doing that?

**Comment by foolip** [comment]
I see, this repo uses a webhook.

**Comment by foolip** [comment]
https://github.com/whatwg/whatwg.org/pull/62

**Comment by foolip** [comment]
Fixed by https://github.com/whatwg/whatwg.org/pull/62
