### ISSUE TITLE
Create fingerprint.svg

### ISSUE THREAD

**Issue by annevk** [whatwg/resources.whatwg.org#49]
Based on https://images.whatwg.org/fingerprint.png or something better?

**Comment by zcorpan** [comment]
https://pixabay.com/p-160979/ ? I have the SVG downloaded, can get it down to 20.5kb.

**Comment by annevk** [comment]
WFM

**Comment by annevk** [comment]
@tabatkins, thoughts?

**Comment by domenic** [comment]
It seems bad to move from 3.3 KB to 20.5 KB.

**Comment by zcorpan** [comment]
OK I made a new one instead, I'll create a PR...
