### ISSUE TITLE
Add a simple service worker for offline reading of all specs

### ISSUE THREAD

**Issue by domenic** [whatwg/resources.whatwg.org#6]
Seems like a fun exercise.

I wonder if we could get @jakearchibald to volunteer to do this?

**Comment by domenic** [comment]
I'm going to try this, first on streams, as a bit of a holiday project.

One thing to consider is that we could make loading spec1.spec.whatwg.org also cache spec2.spec.whatwg.org, but only by spawning an iframe for spec2.spec.whatwg.org. I'm not sure if that's worth it. For now I'll leave that out.

**Comment by annevk** [comment]
An interesting thing we can do is cache all subresources through foreign fetch so they are shared across all standards. Not supported yet by any implementation unfortunately.

**Comment by domenic** [comment]
Yeah, I asked around about how to do that in the present day and was told iframes were the answer.

**Comment by domenic** [comment]
Let's move this to https://github.com/whatwg/meta/issues/3

**Comment by jakearchibald** [comment]
I totally missed this issue back in 2015, sorry 😢
