### ISSUE TITLE
Customize nginx directory listings (e.g., use WHATWG green)

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/resources.whatwg.org#64]
See https://github.com/whatwg/whatwg.org/issues/84#issuecomment-328783329. With some minimal CSS, we can customize the styling of nginx directory listings for, e.g., https://resources.whatwg.org/ and https://images.whatwg.org/ and https://n.whatwg.org/

**Comment by annevk** [comment]
This should probably be in whatwg/whatwg.org as well as this repository is obsolete.

**Comment by sideshowbarker** [comment]
This issue was moved to whatwg/whatwg.org#91
