### ISSUE TITLE
dfn.js should not include references in class="indexlist" containers

### ISSUE THREAD

**Issue by domenic** [whatwg/resources.whatwg.org#8]
That is what Bikeshed producers for its "Terms defined by this specification" indices, which when they show up in the dfn.js list just end up being clutter.

**Comment by annevk** [comment]
Can we also exclude "note"? This should be easily fixable by changing the code around where it deals with "no-backref".

**Comment by zcorpan** [comment]
The indices were fixed in https://github.com/whatwg/resources.whatwg.org/commit/b39d40c5e77f8ce0119eadc864364f93aa4f7979 but not notes.

**Comment by domenic** [comment]
I'm not sure we should exclude "note" (or "example")... Sometimes it is useful to find those. I've explicitly marked some as no-backref when they're definitely not useful (e.g. using specific element names in custom element examples) but I think for example it's useful when looking up "incumbent settings object" to see all the examples and notes that use it to clarify what's going on.

**Comment by zcorpan** [comment]
OK, yeah.
