### ISSUE TITLE
Bug filer should include a link to the dated version of the spec

### ISSUE THREAD

**Issue by zcorpan** [whatwg/resources.whatwg.org#9]
When filing a bug it is sometimes a good idea to know which version of the spec the reporter was looking at. We could include a rawgit.com link with the right commit instead of pointing to the latest version in the issue.

**Comment by domenic** [comment]
These days you can search for `#commit-snapshot-link` for Streams, Fetch, and URL. Don't forget to append `location.href`. I hope we can update HTML to a similar structure at some point; right now it's dumping things in /commit-snapshots/ but not linking to them.

**Comment by zcorpan** [comment]
> Don't forget to append `location.href`

Do you mean to support multipage? Or append to what?

**Comment by domenic** [comment]
I ... can't remember exactly what I meant :(.
